import React, { useRef, useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { useSandbox } from '../../context/SandboxContext';
import { EvidenceItem } from '../../types/sandbox';
import { isTechnicalTestingComplete, isUiEvidenceComplete } from '../../utils/readiness';
import { QR_API_DOCUMENTATION_URL } from '../../constants/developerResources';

interface UiEvidenceSectionProps { stepNumber?: number; className?: string }
const formatSize = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export const UiEvidenceSection: React.FC<UiEvidenceSectionProps> = ({ stepNumber, className = '' }) => {
  const { state, updateState, addToast } = useSandbox();
  const imageInput = useRef<HTMLInputElement>(null);
  const videoInput = useRef<HTMLInputElement>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const locked = !isTechnicalTestingComplete(state);
  const screenshots = state.uiEvidence?.screenshots ?? (state.uiEvidence?.screenshotAttached ? [{ fileName: state.uiEvidence.screenshotFileName || 'qr-payment-screen.png', fileData: undefined, uploadedAt: new Date().toISOString() }] : []);
  const videoAttached = Boolean(state.uiEvidence?.recordingAttached);
  const complete = isUiEvidenceComplete(state);

  const updateEvidence = (updates: Record<string, unknown>) => updateState({ uiEvidence: { ...(state.uiEvidence || { recordingAttached: false, screenshotAttached: false }), ...updates } });
  const onImages = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (locked) return;
    const files = Array.from(event.target.files || []);
    const valid = files.filter(file => file.type.startsWith('image/') && file.size <= 10 * 1024 * 1024);
    if (valid.length !== files.length) addToast('Some screenshots skipped', 'Use PNG or JPG files up to 10MB.', 'info');
    Promise.all(valid.map(file => new Promise<EvidenceItem>(resolve => { const reader = new FileReader(); reader.onload = () => resolve({ fileName: file.name, fileData: String(reader.result), uploadedAt: new Date().toISOString() }); reader.readAsDataURL(file); }))).then(items => { if (items.length) { updateEvidence({ screenshots: [...screenshots, ...items], screenshotAttached: true, screenshotFileName: items[0].fileName, screenshotFileSize: formatSize(valid[0].size) }); addToast('Screenshots uploaded', `${screenshots.length + items.length} screenshot${screenshots.length + items.length === 1 ? '' : 's'} attached.`, 'success'); } });
    event.target.value = '';
  };
  const onVideo = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || locked) return; if (!['video/mp4', 'video/quicktime'].includes(file.type) || file.size > 50 * 1024 * 1024) { addToast('Video not uploaded', 'Use an MP4 or MOV file up to 50MB.', 'info'); return; } const reader = new FileReader(); reader.onload = () => { updateEvidence({ recordingAttached: true, recordingFileName: file.name, recordingFileSize: formatSize(file.size), recordingFileData: String(reader.result) }); addToast('Video uploaded', 'Your payment flow video is ready.', 'success'); }; reader.readAsDataURL(file); event.target.value = ''; };
  const removeImage = (index: number) => { const next = screenshots.filter((_, itemIndex) => itemIndex !== index); updateEvidence({ screenshots: next, screenshotAttached: next.length > 0, screenshotFileName: next[0]?.fileName, screenshotFileSize: undefined }); };
  const moveImage = (index: number, direction: -1 | 1) => { const next = [...screenshots]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; updateEvidence({ screenshots: next }); };
  const statusText = locked ? 'LOCKED' : complete ? 'EVIDENCE SUBMITTED' : 'READY TO SUBMIT';
  const handleCopyGuideline = () => { if (navigator.clipboard) navigator.clipboard.writeText(QR_API_DOCUMENTATION_URL); addToast('Guideline link copied', 'Share the official PayWay QR UI requirements with your team.', 'success'); };
  return <div id="ui-evidence-section" className={className}>
    <div className="mb-4 flex flex-col gap-3 rounded-xl border border-slate-200 bg-slate-50/80 p-4 sm:flex-row sm:items-center sm:justify-between">
      <div><p className="text-sm font-bold text-slate-900">Follow the PayWay QR UI guideline</p><p className="mt-1 text-xs leading-relaxed text-slate-600">Review the official layout, spacing, and branding requirements before recording or capturing your UI.</p></div>
      <div className="flex shrink-0 items-center gap-2"><a href={QR_API_DOCUMENTATION_URL} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-lg bg-[#00B4CC] px-3 py-2 text-xs font-semibold text-white hover:bg-[#009cb2]">View UI guideline <ExternalLink className="h-3.5 w-3.5" /></a><button type="button" onClick={handleCopyGuideline} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Copy link</button></div>
    </div>
    <div className="rounded-xl border border-slate-200/90 bg-white p-6 shadow-2xs">
      <div className="mb-5 flex items-start justify-between gap-4"><div>{stepNumber && <div className="mb-1 flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#00B4CC] text-xs font-bold text-white">{stepNumber}</span><h3 className="text-base font-bold text-slate-900">Stage {stepNumber}: Submit UI evidence</h3></div>}<p className="mt-1 text-xs leading-relaxed text-slate-500">Show us how PayWay is implemented in your product.</p></div><span className={`shrink-0 rounded border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${locked ? 'border-slate-200 bg-slate-50 text-slate-500' : complete ? 'border-emerald-300 bg-emerald-50 text-emerald-700' : 'border-cyan-200 bg-cyan-50 text-cyan-700'}`}>{statusText}</span></div>
      <div className={`mb-5 rounded-lg border px-4 py-3 text-xs leading-relaxed ${locked ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-cyan-100 bg-cyan-50 text-cyan-800'}`}>{locked ? 'Complete all technical tests to unlock evidence submission.' : 'Provide screenshots or a video. Choose the format that best demonstrates your PayWay integration.'}</div>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <section className={`rounded-xl border border-slate-200 p-5 ${locked ? 'bg-slate-50' : 'bg-white'}`}><div className="mb-2 flex items-center justify-between gap-2"><h4 className="text-sm font-bold text-slate-900">Screenshots ({screenshots.length} uploaded)</h4><span className="text-[10px] font-bold uppercase text-slate-400">Optional if video</span></div><p className="mb-4 text-xs leading-relaxed text-slate-500">Upload screenshots that clearly show how PayWay is integrated into your product.</p><input ref={imageInput} type="file" accept="image/png,image/jpeg" multiple className="hidden" onChange={onImages} /><button type="button" disabled={locked} onClick={() => imageInput.current?.click()} className="w-full rounded-lg border border-dashed border-slate-300 py-3 text-xs font-semibold text-slate-700 disabled:cursor-not-allowed disabled:opacity-50">{screenshots.length ? 'Add more screenshots' : 'Upload screenshots'}</button>{screenshots.length > 0 && <div className="mt-4 grid grid-cols-3 gap-2">{screenshots.map((item, index) => <div key={`${item.fileName}-${index}`} className="group relative overflow-hidden rounded-lg border border-slate-200 bg-slate-100"><button type="button" onClick={() => item.fileData && setPreview(item.fileData)} className="block aspect-square w-full">{item.fileData ? <img src={item.fileData} alt={item.fileName} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-[10px] text-slate-500">Preview</div>}</button><button type="button" onClick={() => removeImage(index)} className="absolute right-1 top-1 rounded bg-white/90 px-1.5 py-0.5 text-[10px] text-rose-600">Remove</button><div className="flex justify-center gap-2 py-1 text-[10px]"><button type="button" disabled={index === 0} onClick={() => moveImage(index, -1)} aria-label="Move screenshot left">←</button><button type="button" disabled={index === screenshots.length - 1} onClick={() => moveImage(index, 1)} aria-label="Move screenshot right">→</button></div></div>)}</div>}</section>
        <section className={`rounded-xl border border-slate-200 p-5 ${locked ? 'bg-slate-50' : 'bg-white'}`}><div className="mb-2 flex items-center justify-between gap-2"><h4 className="text-sm font-bold text-slate-900">Video demonstration</h4><span className="text-[10px] font-bold uppercase text-slate-400">Optional if screenshots</span></div><p className="mb-4 text-xs leading-relaxed text-slate-500">Upload a video showing how PayWay works in your product.</p><input ref={videoInput} type="file" accept="video/mp4,video/quicktime" className="hidden" onChange={onVideo} />{videoAttached ? <div className="flex items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50 p-3"><div><p className="text-xs font-semibold text-emerald-800">Evidence submitted</p><p className="mt-1 max-w-40 truncate text-[11px] text-emerald-700">{state.uiEvidence?.recordingFileName}</p></div><button type="button" onClick={() => updateEvidence({ recordingAttached: false, recordingFileName: undefined, recordingFileSize: undefined, recordingFileData: undefined })} className="text-xs font-semibold text-rose-600">Remove</button></div> : <button type="button" disabled={locked} onClick={() => videoInput.current?.click()} className="w-full rounded-lg border border-dashed border-slate-300 py-3 text-xs font-semibold text-slate-700 disabled:cursor-not-allowed disabled:opacity-50">Upload video</button>}<p className="mt-3 text-[11px] text-slate-400">MP4 or MOV. Maximum 50MB.</p></section>
      </div>
    </div>{preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={() => setPreview(null)}><img src={preview} alt="Screenshot preview" className="max-h-[85vh] max-w-[90vw] rounded-xl bg-white object-contain" /></div>}
  </div>;
};
